using System;
using System.ComponentModel.DataAnnotations;

namespace Gaby.Shared.Model
{
	public class Equipment
	{
        [Key]
        /// <summary>
        /// Autogenerated ID for the equipment.
        /// </summary>
        public int EquipmentId { get; set; }

        /// <summary>
        /// An identificative or descriptive name of the equipment.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Number of gym equipment of this specific type.
        /// </summary>
        public int Count { get; set; }


        /// <summary>
        /// Returns the repairs that have been made to the equipment.
        /// </summary>
        public ICollection<EquipmentRepair>? Repairs { get; set; }


        /// <summary>
        /// Returns the expenses caused by the equipment.
        /// </summary>
        public ICollection<EquipmentExpense>? Expenses { get; set; }
    }
}

