using System;
using System.ComponentModel.DataAnnotations;
using Gaby.Shared.Utils;

namespace Gaby.Shared.Model
{
	public class Expense
	{
        /// <summary>
        /// Autogenerated Id of the expense.
        /// </summary>
        public int ExpenseId { get; set; }

        /// <summary>
        /// The amount of money of the expense.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Returns the date of the expense.
        /// </summary>
        
        public BasicDate ExpenseDate { get; set; }


        [Required]
        public virtual ExpenseType ExpenseType { get; set; }

        
        public ICollection<Payment> Payments { get; set; }
    }
}

